# Generated by Django 5.1.4 on 2025-01-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battery_types', '0002_alter_batterytype_internal_resistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_title', models.CharField(max_length=255, verbose_name='Название места установки')),
                ('system_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название системы')),
                ('nesting_level', models.PositiveIntegerField(verbose_name='Уровень вложенности')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='journal.installationlocation', verbose_name='Родительское место')),
            ],
            options={
                'verbose_name': 'Место установки',
                'verbose_name_plural': 'Места установки',
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('battery_number', models.CharField(max_length=255, verbose_name='Номер АКБ')),
                ('manufacture_date', models.DateField(verbose_name='Дата изготовления')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='Дата приемки')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Дата установки на оборудование')),
                ('battery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery_types.batterytype', verbose_name='Тип АКБ')),
                ('installation_location', models.ManyToManyField(related_name='batteries', to='journal.installationlocation', verbose_name='Места установки')),
            ],
            options={
                'verbose_name': 'АКБ',
                'verbose_name_plural': 'АКБ',
            },
        ),
        migrations.CreateModel(
            name='TestingDBT12D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_date', models.DateField(verbose_name='Дата тестирования')),
                ('SOH', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Состояние здоровья (SOH)')),
                ('SOC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Состояние заряда (SOC)')),
                ('VOL', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Напряжение (VOL)')),
                ('R', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сопротивление (R)')),
                ('STD', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стандарт (STD)')),
                ('CCA', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Холодный ток запуска (CCA)')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.battery', verbose_name='АКБ')),
            ],
            options={
                'verbose_name': 'Тестирование DBT12D',
                'verbose_name_plural': 'Тестирования DBT12D',
            },
        ),
        migrations.CreateModel(
            name='TestingIC105',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_date', models.DateField(verbose_name='Дата тестирования')),
                ('SOH', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Состояние здоровья (SOH)')),
                ('VOL', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Напряжение (VOL)')),
                ('R', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сопротивление (R)')),
                ('STD', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стандарт (STD)')),
                ('CCA', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Холодный ток запуска (CCA)')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.battery', verbose_name='АКБ')),
            ],
            options={
                'verbose_name': 'Тестирование IC-105',
                'verbose_name_plural': 'Тестирования IC-105',
            },
        ),
    ]
