# Generated by Django 5.1.4 on 2025-01-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationlocation',
            name='nesting_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень вложенности'),
        ),
    ]
