# Generated by Django 5.1.4 on 2025-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_batteryinstallationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='installation_location',
        ),
        migrations.AlterField(
            model_name='batteryinstallationhistory',
            name='installation_date',
            field=models.DateField(verbose_name='Дата установки'),
        ),
    ]
