# Generated by Django 5.1.4 on 2025-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_remove_battery_installation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='battery_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Номер АКБ'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изготовления'),
        ),
    ]
