# Generated by Django 5.1.4 on 2025-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_battery_battery_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryinstallationhistory',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата установки'),
        ),
    ]
