# Generated by Django 5.1.4 on 2025-02-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_batteryinstallationhistory_installation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Серийный номер'),
        ),
    ]
