# Generated by Django 5.1.4 on 2025-09-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_types', '0003_alter_batterytype_lifespan'),
        ('journal', '0007_alter_battery_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='serial_number',
        ),
        migrations.CreateModel(
            name='SerialParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('manufacture_date', models.DateField(verbose_name='Дата изготовления')),
                ('battery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery_types.batterytype', verbose_name='Тип АКБ')),
            ],
            options={
                'verbose_name': 'Серийный параметр',
                'verbose_name_plural': 'Серийные параметры',
            },
        ),
        migrations.AddField(
            model_name='battery',
            name='serial_parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.serialparameters', verbose_name='Серийные параметры'),
        ),
    ]
