# Generated by Django 5.1.4 on 2025-12-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_remove_battery_manufacture_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='installation_date',
        ),
    ]
