# Generated by Django 5.1.4 on 2025-12-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_types', '0004_batterytype_weight'),
        ('journal', '0009_remove_battery_installation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialparameters',
            name='battery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery_types.batterytype', verbose_name='Тип АБ'),
        ),
    ]
