# Generated by Django 5.1.4 on 2025-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_alter_serialparameters_battery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationlocation',
            name='battery_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество АБ'),
        ),
        migrations.AddField(
            model_name='installationlocation',
            name='location_type',
            field=models.CharField(choices=[('container', 'Шкаф'), ('virtual', 'Промежуточное место, путь')], default='container', max_length=20, verbose_name='Тип места установки'),
        ),
        migrations.AddField(
            model_name='installationlocation',
            name='nominal_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Номинальная емкость АБ, А⋅ч'),
        ),
        migrations.AddField(
            model_name='installationlocation',
            name='system_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название системы'),
        ),
        migrations.AlterField(
            model_name='installationlocation',
            name='system_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddConstraint(
            model_name='installationlocation',
            constraint=models.UniqueConstraint(fields=('location_title', 'location_type', 'system_name'), name='unique_installation_location'),
        ),
    ]
