# Generated by Django 5.1.4 on 2026-01-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_installationlocation_battery_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qr_codes/batteries/', verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='battery',
            name='qr_data_hash',
            field=models.CharField(blank=True, editable=False, help_text='Для определения, нужно ли перегенерировать QR', max_length=64, null=True, verbose_name='Хэш данных QR'),
        ),
    ]
