# Generated by Django 5.1.4 on 2025-01-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('battery_type_title', models.CharField(max_length=255, verbose_name='Модель')),
                ('nominal_voltage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Номинальное напряжение, В')),
                ('elements_count', models.IntegerField(verbose_name='Количество элементов в АБ')),
                ('lifespan', models.IntegerField(verbose_name='Скрок службы, лет')),
                ('nominal_capacity_20', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Номинальная ёмкость при 20-ти часовом разряде')),
                ('nominal_capacity_10', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Номинальная ёмкость при 10-ти часовом разряде')),
                ('nominal_capacity_5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Номинальная ёмкость при 5-ти часовом разряде')),
                ('self_discharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Саморазряд, %')),
                ('internal_resistance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Внутреннее сопротивление, Ом')),
            ],
            options={
                'verbose_name': 'Тип АБ',
                'verbose_name_plural': 'Типы АБ',
            },
        ),
    ]
