# Generated by Django 5.1.4 on 2025-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterytype',
            name='internal_resistance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Внутреннее сопротивление, мОм'),
        ),
    ]
