# Generated by Django 5.1.4 on 2025-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_types', '0002_alter_batterytype_internal_resistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterytype',
            name='lifespan',
            field=models.IntegerField(verbose_name='Срок службы, лет'),
        ),
    ]
