# Generated by Django 5.1.4 on 2025-12-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_types', '0003_alter_batterytype_lifespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterytype',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес АБ, кг'),
        ),
    ]
