# Generated by Django 5.1.4 on 2025-12-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_types', '0004_batterytype_weight'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batterytype',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'battery_type_title'), name='unique_battery_type'),
        ),
    ]
