# Generated by Django 5.1.4 on 2025-12-05 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление')], max_length=20, verbose_name='Тип события')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Детали (JSON)')),
                ('color', models.CharField(default='yellow', max_length=20, verbose_name='Цвет события')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-timestamp'],
            },
        ),
    ]
