# Generated by Django 5.1.4 on 2025-12-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
    ]
