# Generated by Django 5.1.4 on 2025-12-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект (снимок)'),
        ),
    ]
