# Generated by Django 5.1.4 on 2025-12-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_object_repr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
