# Generated by Django 5.1.4 on 2025-12-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='details',
        ),
        migrations.AddField(
            model_name='event',
            name='changed_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='Изменённые поля'),
        ),
        migrations.AddField(
            model_name='event',
            name='new_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Новые данные'),
        ),
        migrations.AddField(
            model_name='event',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Старые данные'),
        ),
        migrations.AlterField(
            model_name='event',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект'),
        ),
    ]
