# Generated by Django 5.1.4 on 2025-12-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_details_event_changed_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full_representation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
