# Generated by Django 5.1.4 on 2025-01-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Служба', 'verbose_name_plural': 'Службы'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='subdepartment',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='Служба'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_phone_number',
            field=models.CharField(max_length=14, verbose_name='Сотовый номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.job', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Домашний номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subdepartment', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sur_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_title',
            field=models.CharField(max_length=255, verbose_name='Название службы'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_title',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_title',
            field=models.CharField(max_length=20, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Служба'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='subdepartment_title',
            field=models.CharField(max_length=255, verbose_name='Название участка'),
        ),
    ]
