# Generated by Django 5.1.4 on 2025-11-01 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_department_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name="Цвет (Bootstrap класс, например 'warning' или 'success')")),
            ],
            options={
                'verbose_name': 'Статус ошибки',
                'verbose_name_plural': 'Статусы ошибок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа ошибки')),
            ],
            options={
                'verbose_name': 'Тип ошибки',
                'verbose_name_plural': 'Типы ошибок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.errorstatus', verbose_name='Статус')),
                ('error_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.errortype', verbose_name='Тип ошибки')),
            ],
            options={
                'verbose_name': 'Сообщение об ошибке',
                'verbose_name_plural': 'Сообщения об ошибках',
                'ordering': ['-created_at'],
            },
        ),
    ]
