# Generated by Django 5.1.4 on 2025-12-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_errorstatus_errortype_errorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Обратная связь'),
        ),
    ]
