# Generated by Django 5.1.4 on 2025-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_errorreport_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Обратная связь'),
        ),
    ]
